Repository PrafullRaj/flame-coder, pull requests merged in 2022-10, with the labels that each got.

#1 Create bouncing_ball.py
  python/Bouncing Ball/bouncing_ball.py
Labels: documentation, hacktoberfest-accepted

#2 Create tower_of_hanoi.py
  python/tower_of_hanoi.py
Labels: documentation, hacktoberfest-accepted

#3 Create Asterisk_pattern.py
  python/Asterisk_pattern.py
Labels: documentation, hacktoberfest-accepted

#4 Create Clock_App.py
  python/Clock_App.py
Labels: documentation, hacktoberfest-accepted

#5 Create armstrong_number.py
  python/armstrong_number.py
Labels: documentation, hacktoberfest-accepted

#7 Added code for a bouncy ball
  python/bouncing_ball.py
Labels: documentation, good first issue, hacktoberfest-accepted

#8 Create multiplication_table.py
  python/multiplication_table.py
Labels: documentation, hacktoberfest-accepted

#9 Create quadratic_equation.py
  python/quadratic_equation.py
Labels: documentation, hacktoberfest-accepted

#10 Create palindrome.py
  python/palindrome.py
Labels: documentation, hacktoberfest-accepted

#11 Create pointers.cpp
  C++/pointers.cpp
Labels: documentation, good first issue, hacktoberfest-accepted

#14 Create star_pattern.cpp
  C++/star_pattern.cpp
Labels: documentation, hacktoberfest-accepted

#13 Create class_matrix.cpp
  C++/class_matrix.cpp
Labels: documentation, hacktoberfest-accepted

#12 Create class_list_of_managers.cpp
  C++/class_list_of_managers.cpp
Labels: documentation, hacktoberfest-accepted

#15 Created a JAVA folder and added important scripts
  java/BenjaminBulbs.java
  java/Largest3.java
  java/PrimeChecker.java
  java/digitCounter.java
  java/eachDigit.java
  java/inverseNumber.java
  java/lcm_gcd.java
  java/primeFactorisation.java
  java/rotateNumber.java
Labels: good first issue, hacktoberfest-accepted, hactoberfest

#16 Create Delete_element_from_Array.cpp
  C++/Delete_element_from_Array.cpp
Labels: documentation, hacktoberfest-accepted, hactoberfest

#17 Create ShopingList.cpp
  ShopingList.cpp
Labels: documentation, enhancement, hacktoberfest-accepted, hactoberfest

#18 Create CreateanduseArray.cpp
  C++/CreateanduseArray.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#19 Create FindMaximum.cpp
  C++/FindMaximum.cpp
Labels: documentation, enhancement, hacktoberfest-accepted, hactoberfest

#20 Create SwapprivateData.cpp
  C++/SwapprivateData.cpp
Labels: good first issue, hacktoberfest-accepted, hactoberfest

#24 Create gcd.cpp
  C++/gcd.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#23 Createsumofnaturalnumber.cpp
  C++/sumofnaturalnumber.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#22 Create evenorodd.cpp
  C++/evenorodd.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#21 Create findingquitient.cpp
  C++/findingquitient.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#31 Update star_pattern.cpp
  C++/star_pattern.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#30 Update gcd.cpp
  C++/gcd.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#29 Update Delete_element_from_Array.cpp
  C++/Delete_element_from_Array.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#28 Update FindMaximum.cpp
  C++/FindMaximum.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#27 Create SubstractionLinkedList.cpp
  C++/SubstractionLinkedList.cpp
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#26 Create 2022_hactoberfest
  C++/2022_hactoberfest
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#25 Create 2022_Hactober
  C++/2022_Hactober
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hactoberfest

#32 Create Anurupa_hactober
  Anurupa_hactober
Labels: documentation, good first issue, hacktoberfest-accepted, hactoberfest
